language: java

os: linux
services:
  - xvfb

jdk:
  - openjdk8

script:
  - mvn test

branches:

  only:
    - featQA

  except:
    - master
    - devel
    - featBizlogic
    - featFestivalUX
    - featAdmin
    - featFilter